repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.64.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
      - id: terraform_fmt
      #- id: terraform_docs
      - id: terraform_validate
      - id: terraform_tflint
        args:
          - --args=--config=./tmp/tflint.hcl

  - repo: https://github.com/bridgecrewio/checkov.git
    rev: 2.0.872 # change to tag or sha
    hooks:
      - id: checkov
